/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cubes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new solved cube and returns its state. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Optional settings; defaults to a 3×3 cube. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCubeRequest"];
                    "text/json": components["schemas"]["CreateCubeRequest"];
                    "application/*+json": components["schemas"]["CreateCubeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cubes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current state of a cube. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Deletes a cube session. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cubes/{id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applies moves in Singmaster notation (e.g. `"F R' U2"`) to a cube. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The moves to apply. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApplyMovesRequest"];
                    "text/json": components["schemas"]["ApplyMovesRequest"];
                    "application/*+json": components["schemas"]["ApplyMovesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cubes/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undoes the most recently applied move. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cubes/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restores the cube to its solved state and clears the move history. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cubes/{id}/scramble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applies a random scramble to the cube. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The cube session id. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Optional scramble settings. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ScrambleRequest"];
                    "text/json": components["schemas"]["ScrambleRequest"];
                    "application/*+json": components["schemas"]["ScrambleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CubeStateDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for applying moves to a cube. */
        ApplyMovesRequest: {
            /** @description The moves in Singmaster notation, e.g. `"F R' U2"`. */
            moves: string;
        };
        /** @description Request body for creating a cube session. */
        CreateCubeRequest: {
            /**
             * Format: int32
             * @description The cube size; the classic 3×3 cube when omitted.
             */
            size?: number | null;
        };
        /** @description The client-facing representation of a cube session. */
        CubeStateDto: {
            /**
             * Format: uuid
             * @description The session identifier.
             */
            id: string;
            /**
             * Format: int32
             * @description The cube size (3 for the classic cube).
             */
            size: number;
            /** @description Whether every face currently shows a single colour. */
            isSolved: boolean;
            /**
             * @description The six faces keyed by name (`up`, `down`, `front`, `back`,
             *     `left`, `right`), each as rows of colour letters from top to bottom,
             *     e.g. `"WWW"` — using W, Y, G, B, R, O.
             */
            faces: {
                [key: string]: string[];
            };
            /** @description Every move applied since creation or the last reset, in Singmaster notation. */
            history: string[];
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Request body for scrambling a cube. */
        ScrambleRequest: {
            /**
             * Format: int32
             * @description The number of random moves; a sensible default when omitted.
             */
            length?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
